### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by paulzay**
#### What does this PR do?
Create a Youtube Clone
#### Description of Task to be completed?
1. Add basic structure 
2. Create a Navigation bar
3. Create the main content 
4. Create sidebar
5. Add footer
6. Add the README file.
#### How should this be manually tested?
# Clone this repository
$ git clone https://github.com/paulzay/youtube

# Go into the repository
$ cd youtube
#### Screenshots
Screenshot (327)

### CODE REVIEW

**Comment by santiago-dev96** [comment]
## Pull Request under Review by @santiago-rodrig (TSE)

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
# Good work! But...
1. You must use a descriptive PR (Pull Request) title as requested [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
2. The avatar for the user that uploaded the video is not present
requirement image
3. There is not a visible subscribe button
requirement image

Please implement the required changes and resubmit the CRR (Code Review Request).

### My review process
```bash
git clone https://github.com/paulzay/youtube.git && \
cd youtube && git checkout README && \
xdg-open index.html
```

After seeing the page I notice that there is not an avatar image nor a subscribe button over here

image

### By the way...

Overall the project is great, also the PR summary and README showcase the skill of the attention to detail, congratulations from my part. I almost forgot; the live link is not working.

**Comment by trekab** [comment]
# Changes Required!
Hello @Haroonabdulrazaq and @paulzay, well done with adding your current changes to the correct PR. There are some changes we need to make to the project. These include;
- [ ] Make sure that HTML passes the [HTML validator](https://validator.w3.org/#validate_by_upload) tests.
- [ ] The navigation should have at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar([Read more](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/)). I don't see them on [your clone](https://rawcdn.githack.com/paulzay/youtube/0d3d82fed4d6164e52b1ea4a338ca8d84ca8fb0b/index.html?)
- [ ] The main video section should have a like and dislike icons([Read more](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/)).
- [ ] The main video section should have a share button([Read more](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/)).
- [ ] The main video section should show the avatar of the user who uploaded the video([Read more](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/)).
- [ ] The main video section should have a subscribe button(__not image__). ([Read more](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

__Kindly work on the required changes and submit another code review request__
_Feel free to contact me on slack if you need more info about this review_
__Treasure Kabareebe__

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

Nice job working with the previous reviews and getting the project to this level.🚀

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Pull request merged**
